// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Film struct {
	ID           string  `json:"id"`
	Title        string  `json:"title"`
	EpisodeID    *int    `json:"episode_id"`
	OpeningCrawl *string `json:"opening_crawl"`
	Director     *string `json:"director"`
	Producer     *string `json:"producer"`
	ReleaseDate  *string `json:"release_date"`
}

type PageInfo struct {
	HasNextPage     bool   `json:"hasNextPage"`
	HasPreviousPage bool   `json:"hasPreviousPage"`
	StartCursor     string `json:"startCursor"`
	EndCursor       string `json:"endCursor"`
}

type People struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	BirthYear *string `json:"birth_year"`
	EyeColor  *string `json:"eye_color"`
	Gender    *string `json:"gender"`
	HairColor *string `json:"hair_color"`
	Height    *string `json:"height"`
	Mass      *string `json:"mass"`
	SkinColor *string `json:"skin_color"`
	Films     []*Film `json:"films"`
}

type PeopleConnection struct {
	PageInfo   *PageInfo     `json:"pageInfo"`
	Edges      []*PeopleEdge `json:"edges"`
	TotalCount int           `json:"totalCount"`
}

type PeopleEdge struct {
	Node   *People `json:"node"`
	Cursor string  `json:"cursor"`
}
